import PageTracker from '@/components/PageTracker/PageTracker'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <PageTracker><html lang="en">
      <body>{children}</body>
    </html>
    </PageTracker>
  )
}
